// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package rtc

import (
	sfu_events "github.com/GetStream/protocol/protobuf/video/sfu/event"

	"github.com/GetStream/getstream-go-webrtc/coordinator/models"
)

// callEventDispatchCase registers a handler for one member of CallEvents.
type callEventDispatchCase struct {
	// Type is the constraint member, for failure messages.
	Type string
	// Register calls dispatchCallEvent with that member as T.
	Register func(*Call) (func(), bool)
}

// callEventDispatchCases covers every type CallEvents admits.
var callEventDispatchCases = []callEventDispatchCase{
	{
		Type: "*models.BlockedUserEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.BlockedUserEvent) {})
		},
	},
	{
		Type: "*models.CallAcceptedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallAcceptedEvent) {})
		},
	},
	{
		Type: "*models.CallClosedCaptionsFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallClosedCaptionsFailedEvent) {})
		},
	},
	{
		Type: "*models.CallClosedCaptionsStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallClosedCaptionsStartedEvent) {})
		},
	},
	{
		Type: "*models.CallClosedCaptionsStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallClosedCaptionsStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallCreatedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallCreatedEvent) {})
		},
	},
	{
		Type: "*models.CallDTMFEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallDTMFEvent) {})
		},
	},
	{
		Type: "*models.CallDeletedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallDeletedEvent) {})
		},
	},
	{
		Type: "*models.CallEndedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallEndedEvent) {})
		},
	},
	{
		Type: "*models.CallFrameRecordingFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallFrameRecordingFailedEvent) {})
		},
	},
	{
		Type: "*models.CallFrameRecordingFrameReadyEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallFrameRecordingFrameReadyEvent) {})
		},
	},
	{
		Type: "*models.CallFrameRecordingStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallFrameRecordingStartedEvent) {})
		},
	},
	{
		Type: "*models.CallFrameRecordingStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallFrameRecordingStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallHLSBroadcastingFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallHLSBroadcastingFailedEvent) {})
		},
	},
	{
		Type: "*models.CallHLSBroadcastingStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallHLSBroadcastingStartedEvent) {})
		},
	},
	{
		Type: "*models.CallHLSBroadcastingStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallHLSBroadcastingStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallLiveStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallLiveStartedEvent) {})
		},
	},
	{
		Type: "*models.CallMemberAddedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallMemberAddedEvent) {})
		},
	},
	{
		Type: "*models.CallMemberRemovedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallMemberRemovedEvent) {})
		},
	},
	{
		Type: "*models.CallMemberUpdatedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallMemberUpdatedEvent) {})
		},
	},
	{
		Type: "*models.CallMemberUpdatedPermissionEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallMemberUpdatedPermissionEvent) {})
		},
	},
	{
		Type: "*models.CallMissedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallMissedEvent) {})
		},
	},
	{
		Type: "*models.CallModerationBlurEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallModerationBlurEvent) {})
		},
	},
	{
		Type: "*models.CallModerationWarningEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallModerationWarningEvent) {})
		},
	},
	{
		Type: "*models.CallNotificationEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallNotificationEvent) {})
		},
	},
	{
		Type: "*models.CallReactionEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallReactionEvent) {})
		},
	},
	{
		Type: "*models.CallRecordingFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRecordingFailedEvent) {})
		},
	},
	{
		Type: "*models.CallRecordingReadyEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRecordingReadyEvent) {})
		},
	},
	{
		Type: "*models.CallRecordingStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRecordingStartedEvent) {})
		},
	},
	{
		Type: "*models.CallRecordingStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRecordingStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallRejectedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRejectedEvent) {})
		},
	},
	{
		Type: "*models.CallRingEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRingEvent) {})
		},
	},
	{
		Type: "*models.CallRtmpBroadcastFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRtmpBroadcastFailedEvent) {})
		},
	},
	{
		Type: "*models.CallRtmpBroadcastStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRtmpBroadcastStartedEvent) {})
		},
	},
	{
		Type: "*models.CallRtmpBroadcastStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallRtmpBroadcastStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallSessionEndedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallSessionEndedEvent) {})
		},
	},
	{
		Type: "*models.CallSessionParticipantCountsUpdatedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallSessionParticipantCountsUpdatedEvent) {})
		},
	},
	{
		Type: "*models.CallSessionParticipantJoinedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallSessionParticipantJoinedEvent) {})
		},
	},
	{
		Type: "*models.CallSessionParticipantLeftEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallSessionParticipantLeftEvent) {})
		},
	},
	{
		Type: "*models.CallSessionStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallSessionStartedEvent) {})
		},
	},
	{
		Type: "*models.CallStatsReportReadyEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallStatsReportReadyEvent) {})
		},
	},
	{
		Type: "*models.CallTranscriptionFailedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallTranscriptionFailedEvent) {})
		},
	},
	{
		Type: "*models.CallTranscriptionReadyEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallTranscriptionReadyEvent) {})
		},
	},
	{
		Type: "*models.CallTranscriptionStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallTranscriptionStartedEvent) {})
		},
	},
	{
		Type: "*models.CallTranscriptionStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallTranscriptionStoppedEvent) {})
		},
	},
	{
		Type: "*models.CallUpdatedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallUpdatedEvent) {})
		},
	},
	{
		Type: "*models.CallUserFeedbackSubmittedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallUserFeedbackSubmittedEvent) {})
		},
	},
	{
		Type: "*models.CallUserMutedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CallUserMutedEvent) {})
		},
	},
	{
		Type: "*models.ClosedCaptionEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.ClosedCaptionEvent) {})
		},
	},
	{
		Type: "*models.CustomVideoEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.CustomVideoEvent) {})
		},
	},
	{
		Type: "*models.IngressErrorEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.IngressErrorEvent) {})
		},
	},
	{
		Type: "*models.IngressStartedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.IngressStartedEvent) {})
		},
	},
	{
		Type: "*models.IngressStoppedEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.IngressStoppedEvent) {})
		},
	},
	{
		Type: "*models.KickedUserEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.KickedUserEvent) {})
		},
	},
	{
		Type: "*models.PermissionRequestEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.PermissionRequestEvent) {})
		},
	},
	{
		Type: "*models.UnblockedUserEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.UnblockedUserEvent) {})
		},
	},
	{
		Type: "*models.UpdatedCallPermissionsEvent",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*models.UpdatedCallPermissionsEvent) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_AudioLevelChanged",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_AudioLevelChanged) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_CallEnded",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_CallEnded) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_CallGrantsUpdated",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_CallGrantsUpdated) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ChangePublishOptions",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ChangePublishOptions) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ChangePublishQuality",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ChangePublishQuality) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ConnectionQualityChanged",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ConnectionQualityChanged) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_DominantSpeakerChanged",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_DominantSpeakerChanged) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_Error",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_Error) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_GoAway",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_GoAway) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_HealthCheckResponse",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_HealthCheckResponse) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_IceRestart",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_IceRestart) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_IceTrickle",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_IceTrickle) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_InboundStateNotification",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_InboundStateNotification) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_JoinResponse",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_JoinResponse) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ParticipantJoined",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ParticipantJoined) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ParticipantLeft",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ParticipantLeft) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ParticipantMigrationComplete",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ParticipantMigrationComplete) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_ParticipantUpdated",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_ParticipantUpdated) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_PinsUpdated",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_PinsUpdated) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_PublisherAnswer",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_PublisherAnswer) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_SubscriberOffer",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_SubscriberOffer) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_TrackPublished",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_TrackPublished) {})
		},
	},
	{
		Type: "*sfu_events.SfuEvent_TrackUnpublished",
		Register: func(call *Call) (func(), bool) {
			return dispatchCallEvent(call, func(*sfu_events.SfuEvent_TrackUnpublished) {})
		},
	},
}
