package rtc

import (
	"fmt"

	sfu_events "github.com/GetStream/protocol/protobuf/video/sfu/event"

	"github.com/GetStream/getstream-go-webrtc/coordinator"
	"github.com/GetStream/getstream-go-webrtc/coordinator/models"
	"github.com/GetStream/getstream-go-webrtc/event"
	"github.com/GetStream/getstream-go-webrtc/signal"
)

// Events is an alias for coordinator.Events, representing a set of standard
// events handled by the coordinator.
type Events = coordinator.Events

// CallEvents combines coordinator and signal event interfaces, representing
// events that can occur within a call.
type CallEvents interface {
	coordinator.CallEvents | signal.Events
}

// HandleCoordinatorEvent registers a handler for coordinator events.
// It returns a function to unregister the event handler.
func HandleCoordinatorEvent[T coordinator.Events](client *Client, onEvent func(T)) func() {
	return coordinator.HandleEvent(client.CoordinatorClientInterface, onEvent)
}

// AwaitCoordinatorEvent returns an event awaiter that blocks until an event
// that matches the specified predicate occurs.
func AwaitCoordinatorEvent[T coordinator.Events](client *Client, match func(T) bool) *event.EventAwaiter[T, models.WebsocketEvent] {
	return coordinator.AwaitEvent(client.CoordinatorClientInterface, match)
}

// HandleCallSignalEvent registers a handler for signal events related to a call.
// It returns a function to unregister the event handler.
func HandleCallSignalEvent[T signal.Events](client *Call, onEvent func(T)) func() {
	return signal.HandleEvent(client.Client(), onEvent)
}

// HandleCallCoordinatorEvent registers a handler for coordinator events specific to a call.
// It returns a function to unregister the event handler.
func HandleCallCoordinatorEvent[T coordinator.CallEvents](call *Call, onEvent func(T)) func() {
	return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), onEvent)
}

// AwaitCallSignalEvent returns a signal event awaiter that blocks until a signal event
// that matches the specified predicate occurs within a call context.
func AwaitCallSignalEvent[T signal.Events](call *Call, match func(T) bool) *event.EventAwaiter[T, *sfu_events.SfuEvent] {
	return signal.AwaitEvent(call.Client(), match)
}

// AwaitCallCoordinatorEvent returns a coordinator event awaiter that blocks until a coordinator event
// that matches the specified predicate occurs within a call context.
func AwaitCallCoordinatorEvent[T coordinator.CallEvents](call *Call, match func(T) bool) *event.EventAwaiter[T, models.WebsocketEvent] {
	return coordinator.AwaitCallEvent(call.cc.CoordinatorClientInterface, call.CID(), match)
}

// HandleCallEvent registers a handler for a call event from either family,
// routing coordinator events to the coordinator event store and SFU signal
// events to the signal one. It returns a function to unregister the handler.
//
// The routing switch is generated by internal/cmd/genwsevent from the same
// sources as the CallEvents constraint, so every type the constraint admits has a
// case; see events_dispatch.gen.go. A miss can only mean the generated files are
// stale, which TestCallEventDispatchIsExhaustive catches. At runtime it degrades
// to a logged error and a no-op handler rather than the panic it used to be.
func HandleCallEvent[T CallEvents](client *Call, onEvent func(T)) func() {
	unregister, ok := dispatchCallEvent(client, onEvent)
	if !ok {
		var zero T
		client.logger.Errorw(
			"no dispatch for call event, generated event dispatch is stale: rerun ./generate.sh",
			nil, "event_type", fmt.Sprintf("%T", zero))
		return func() {}
	}
	return unregister
}

// castEventHandlerFunc casts an event handler function from one type to another.
// It is a utility function used to adapt event handlers for different event types.
func castEventHandlerFunc[FromType, ToType any](onEvent func(FromType)) func(ToType) {
	return func(t ToType) {
		onEvent(any(t).(FromType))
	}
}
