// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package rtc

import (
	sfu_events "github.com/GetStream/protocol/protobuf/video/sfu/event"

	"github.com/GetStream/getstream-go-webrtc/coordinator"
	"github.com/GetStream/getstream-go-webrtc/coordinator/models"
	"github.com/GetStream/getstream-go-webrtc/signal"
)

// dispatchCallEvent registers onEvent with the store that carries T: the
// coordinator event store for a coordinator.CallEvents member, the SFU signal
// store for a signal.Events member. It reports whether T was recognised, which
// is always true while this file and both constraints are generated together.
func dispatchCallEvent[T CallEvents](call *Call, onEvent func(T)) (func(), bool) {
	var zero T
	switch any(zero).(type) {
	// coordinator.CallEvents
	case *models.BlockedUserEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.BlockedUserEvent](onEvent)), true
	case *models.CallAcceptedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallAcceptedEvent](onEvent)), true
	case *models.CallClosedCaptionsFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallClosedCaptionsFailedEvent](onEvent)), true
	case *models.CallClosedCaptionsStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallClosedCaptionsStartedEvent](onEvent)), true
	case *models.CallClosedCaptionsStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallClosedCaptionsStoppedEvent](onEvent)), true
	case *models.CallCreatedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallCreatedEvent](onEvent)), true
	case *models.CallDTMFEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallDTMFEvent](onEvent)), true
	case *models.CallDeletedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallDeletedEvent](onEvent)), true
	case *models.CallEndedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallEndedEvent](onEvent)), true
	case *models.CallFrameRecordingFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallFrameRecordingFailedEvent](onEvent)), true
	case *models.CallFrameRecordingFrameReadyEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallFrameRecordingFrameReadyEvent](onEvent)), true
	case *models.CallFrameRecordingStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallFrameRecordingStartedEvent](onEvent)), true
	case *models.CallFrameRecordingStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallFrameRecordingStoppedEvent](onEvent)), true
	case *models.CallHLSBroadcastingFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallHLSBroadcastingFailedEvent](onEvent)), true
	case *models.CallHLSBroadcastingStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallHLSBroadcastingStartedEvent](onEvent)), true
	case *models.CallHLSBroadcastingStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallHLSBroadcastingStoppedEvent](onEvent)), true
	case *models.CallLiveStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallLiveStartedEvent](onEvent)), true
	case *models.CallMemberAddedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallMemberAddedEvent](onEvent)), true
	case *models.CallMemberRemovedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallMemberRemovedEvent](onEvent)), true
	case *models.CallMemberUpdatedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallMemberUpdatedEvent](onEvent)), true
	case *models.CallMemberUpdatedPermissionEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallMemberUpdatedPermissionEvent](onEvent)), true
	case *models.CallMissedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallMissedEvent](onEvent)), true
	case *models.CallModerationBlurEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallModerationBlurEvent](onEvent)), true
	case *models.CallModerationWarningEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallModerationWarningEvent](onEvent)), true
	case *models.CallNotificationEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallNotificationEvent](onEvent)), true
	case *models.CallReactionEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallReactionEvent](onEvent)), true
	case *models.CallRecordingFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRecordingFailedEvent](onEvent)), true
	case *models.CallRecordingReadyEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRecordingReadyEvent](onEvent)), true
	case *models.CallRecordingStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRecordingStartedEvent](onEvent)), true
	case *models.CallRecordingStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRecordingStoppedEvent](onEvent)), true
	case *models.CallRejectedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRejectedEvent](onEvent)), true
	case *models.CallRingEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRingEvent](onEvent)), true
	case *models.CallRtmpBroadcastFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRtmpBroadcastFailedEvent](onEvent)), true
	case *models.CallRtmpBroadcastStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRtmpBroadcastStartedEvent](onEvent)), true
	case *models.CallRtmpBroadcastStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallRtmpBroadcastStoppedEvent](onEvent)), true
	case *models.CallSessionEndedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallSessionEndedEvent](onEvent)), true
	case *models.CallSessionParticipantCountsUpdatedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallSessionParticipantCountsUpdatedEvent](onEvent)), true
	case *models.CallSessionParticipantJoinedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallSessionParticipantJoinedEvent](onEvent)), true
	case *models.CallSessionParticipantLeftEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallSessionParticipantLeftEvent](onEvent)), true
	case *models.CallSessionStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallSessionStartedEvent](onEvent)), true
	case *models.CallStatsReportReadyEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallStatsReportReadyEvent](onEvent)), true
	case *models.CallTranscriptionFailedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallTranscriptionFailedEvent](onEvent)), true
	case *models.CallTranscriptionReadyEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallTranscriptionReadyEvent](onEvent)), true
	case *models.CallTranscriptionStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallTranscriptionStartedEvent](onEvent)), true
	case *models.CallTranscriptionStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallTranscriptionStoppedEvent](onEvent)), true
	case *models.CallUpdatedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallUpdatedEvent](onEvent)), true
	case *models.CallUserFeedbackSubmittedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallUserFeedbackSubmittedEvent](onEvent)), true
	case *models.CallUserMutedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CallUserMutedEvent](onEvent)), true
	case *models.ClosedCaptionEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.ClosedCaptionEvent](onEvent)), true
	case *models.CustomVideoEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.CustomVideoEvent](onEvent)), true
	case *models.IngressErrorEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.IngressErrorEvent](onEvent)), true
	case *models.IngressStartedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.IngressStartedEvent](onEvent)), true
	case *models.IngressStoppedEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.IngressStoppedEvent](onEvent)), true
	case *models.KickedUserEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.KickedUserEvent](onEvent)), true
	case *models.PermissionRequestEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.PermissionRequestEvent](onEvent)), true
	case *models.UnblockedUserEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.UnblockedUserEvent](onEvent)), true
	case *models.UpdatedCallPermissionsEvent:
		return coordinator.HandleCallEvent(call.cc.CoordinatorClientInterface, call.CID(), castEventHandlerFunc[T, *models.UpdatedCallPermissionsEvent](onEvent)), true

	// signal.Events
	case *sfu_events.SfuEvent_AudioLevelChanged:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_AudioLevelChanged](onEvent)), true
	case *sfu_events.SfuEvent_CallEnded:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_CallEnded](onEvent)), true
	case *sfu_events.SfuEvent_CallGrantsUpdated:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_CallGrantsUpdated](onEvent)), true
	case *sfu_events.SfuEvent_ChangePublishOptions:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ChangePublishOptions](onEvent)), true
	case *sfu_events.SfuEvent_ChangePublishQuality:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ChangePublishQuality](onEvent)), true
	case *sfu_events.SfuEvent_ConnectionQualityChanged:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ConnectionQualityChanged](onEvent)), true
	case *sfu_events.SfuEvent_DominantSpeakerChanged:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_DominantSpeakerChanged](onEvent)), true
	case *sfu_events.SfuEvent_Error:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_Error](onEvent)), true
	case *sfu_events.SfuEvent_GoAway:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_GoAway](onEvent)), true
	case *sfu_events.SfuEvent_HealthCheckResponse:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_HealthCheckResponse](onEvent)), true
	case *sfu_events.SfuEvent_IceRestart:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_IceRestart](onEvent)), true
	case *sfu_events.SfuEvent_IceTrickle:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_IceTrickle](onEvent)), true
	case *sfu_events.SfuEvent_InboundStateNotification:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_InboundStateNotification](onEvent)), true
	case *sfu_events.SfuEvent_JoinResponse:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_JoinResponse](onEvent)), true
	case *sfu_events.SfuEvent_ParticipantJoined:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ParticipantJoined](onEvent)), true
	case *sfu_events.SfuEvent_ParticipantLeft:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ParticipantLeft](onEvent)), true
	case *sfu_events.SfuEvent_ParticipantMigrationComplete:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ParticipantMigrationComplete](onEvent)), true
	case *sfu_events.SfuEvent_ParticipantUpdated:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_ParticipantUpdated](onEvent)), true
	case *sfu_events.SfuEvent_PinsUpdated:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_PinsUpdated](onEvent)), true
	case *sfu_events.SfuEvent_PublisherAnswer:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_PublisherAnswer](onEvent)), true
	case *sfu_events.SfuEvent_SubscriberOffer:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_SubscriberOffer](onEvent)), true
	case *sfu_events.SfuEvent_TrackPublished:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_TrackPublished](onEvent)), true
	case *sfu_events.SfuEvent_TrackUnpublished:
		return signal.HandleEvent(call.Client(), castEventHandlerFunc[T, *sfu_events.SfuEvent_TrackUnpublished](onEvent)), true
	default:
		return nil, false
	}
}
