// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/GetStream/getstream-go-webrtc/coordinator"
	models "github.com/GetStream/getstream-go-webrtc/coordinator/models"
	"github.com/GetStream/getstream-go-webrtc/event"
	"sync"
)

// Ensure, that CoordinatorClientInterfaceMock does implement coordinator.CoordinatorClientInterface.
// If this is not the case, regenerate this file with moq.
var _ coordinator.CoordinatorClientInterface = &CoordinatorClientInterfaceMock{}

// CoordinatorClientInterfaceMock is a mock implementation of coordinator.CoordinatorClientInterface.
//
//	func TestSomethingThatUsesCoordinatorClientInterface(t *testing.T) {
//
//		// make and configure a mocked coordinator.CoordinatorClientInterface
//		mockedCoordinatorClientInterface := &CoordinatorClientInterfaceMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ConnectFunc: func(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error) {
//				panic("mock out the Connect method")
//			},
//			DisconnectedFunc: func() <-chan struct{} {
//				panic("mock out the Disconnected method")
//			},
//			FastJoinCallFunc: func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.FastJoinCallResponse, error) {
//				panic("mock out the FastJoinCall method")
//			},
//			GetInterceptorFunc: func() *event.Store[models.WebsocketEvent] {
//				panic("mock out the GetInterceptor method")
//			},
//			JoinCallFunc: func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.JoinCallResponse, error) {
//				panic("mock out the JoinCall method")
//			},
//			WatchCallFunc: func(ctx context.Context, _type string, id string, connectionID string) error {
//				panic("mock out the WatchCall method")
//			},
//		}
//
//		// use mockedCoordinatorClientInterface in code that requires coordinator.CoordinatorClientInterface
//		// and then make assertions.
//
//	}
type CoordinatorClientInterfaceMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ConnectFunc mocks the Connect method.
	ConnectFunc func(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error)

	// DisconnectedFunc mocks the Disconnected method.
	DisconnectedFunc func() <-chan struct{}

	// FastJoinCallFunc mocks the FastJoinCall method.
	FastJoinCallFunc func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.FastJoinCallResponse, error)

	// GetInterceptorFunc mocks the GetInterceptor method.
	GetInterceptorFunc func() *event.Store[models.WebsocketEvent]

	// JoinCallFunc mocks the JoinCall method.
	JoinCallFunc func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.JoinCallResponse, error)

	// WatchCallFunc mocks the WatchCall method.
	WatchCallFunc func(ctx context.Context, _type string, id string, connectionID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Connect holds details about calls to the Connect method.
		Connect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JoinRequest is the joinRequest argument value.
			JoinRequest *models.WSAuthMessage
		}
		// FastJoinCall holds details about calls to the FastJoinCall method.
		FastJoinCall []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// _type is the _type argument value.
			_type string
			// ID is the id argument value.
			ID string
			// JoinCallRequest is the joinCallRequest argument value.
			JoinCallRequest models.JoinCallRequest
		}
		// Disconnected holds details about calls to the Disconnected method.
		Disconnected []struct {
		}
		// GetInterceptor holds details about calls to the GetInterceptor method.
		GetInterceptor []struct {
		}
		// JoinCall holds details about calls to the JoinCall method.
		JoinCall []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// _type is the _type argument value.
			_type string
			// ID is the id argument value.
			ID string
			// JoinCallRequest is the joinCallRequest argument value.
			JoinCallRequest models.JoinCallRequest
		}
		// WatchCall holds details about calls to the WatchCall method.
		WatchCall []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// _type is the _type argument value.
			_type string
			// ID is the id argument value.
			ID string
			// ConnectionID is the connectionID argument value.
			ConnectionID string
		}
	}
	lockClose          sync.RWMutex
	lockConnect        sync.RWMutex
	lockDisconnected   sync.RWMutex
	lockFastJoinCall   sync.RWMutex
	lockGetInterceptor sync.RWMutex
	lockJoinCall       sync.RWMutex
	lockWatchCall      sync.RWMutex
}

// Close calls CloseFunc.
func (mock *CoordinatorClientInterfaceMock) Close() error {
	if mock.CloseFunc == nil {
		panic("CoordinatorClientInterfaceMock.CloseFunc: method is nil but CoordinatorClientInterface.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.CloseCalls())
func (mock *CoordinatorClientInterfaceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Connect calls ConnectFunc.
func (mock *CoordinatorClientInterfaceMock) Connect(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error) {
	if mock.ConnectFunc == nil {
		panic("CoordinatorClientInterfaceMock.ConnectFunc: method is nil but CoordinatorClientInterface.Connect was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		JoinRequest *models.WSAuthMessage
	}{
		Ctx:         ctx,
		JoinRequest: joinRequest,
	}
	mock.lockConnect.Lock()
	mock.calls.Connect = append(mock.calls.Connect, callInfo)
	mock.lockConnect.Unlock()
	return mock.ConnectFunc(ctx, joinRequest)
}

// ConnectCalls gets all the calls that were made to Connect.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.ConnectCalls())
func (mock *CoordinatorClientInterfaceMock) ConnectCalls() []struct {
	Ctx         context.Context
	JoinRequest *models.WSAuthMessage
} {
	var calls []struct {
		Ctx         context.Context
		JoinRequest *models.WSAuthMessage
	}
	mock.lockConnect.RLock()
	calls = mock.calls.Connect
	mock.lockConnect.RUnlock()
	return calls
}

// FastJoinCall calls FastJoinCallFunc.
func (mock *CoordinatorClientInterfaceMock) FastJoinCall(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.FastJoinCallResponse, error) {
	if mock.FastJoinCallFunc == nil {
		panic("CoordinatorClientInterfaceMock.FastJoinCallFunc: method is nil but CoordinatorClientInterface.FastJoinCall was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
	}{
		Ctx:             ctx,
		_type:           _type,
		ID:              id,
		JoinCallRequest: joinCallRequest,
	}
	mock.lockFastJoinCall.Lock()
	mock.calls.FastJoinCall = append(mock.calls.FastJoinCall, callInfo)
	mock.lockFastJoinCall.Unlock()
	return mock.FastJoinCallFunc(ctx, _type, id, joinCallRequest)
}

// FastJoinCallCalls gets all the calls that were made to FastJoinCall.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.FastJoinCallCalls())
func (mock *CoordinatorClientInterfaceMock) FastJoinCallCalls() []struct {
	Ctx             context.Context
	_type           string
	ID              string
	JoinCallRequest models.JoinCallRequest
} {
	var calls []struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
	}
	mock.lockFastJoinCall.RLock()
	calls = mock.calls.FastJoinCall
	mock.lockFastJoinCall.RUnlock()
	return calls
}

// Disconnected calls DisconnectedFunc.
func (mock *CoordinatorClientInterfaceMock) Disconnected() <-chan struct{} {
	if mock.DisconnectedFunc == nil {
		panic("CoordinatorClientInterfaceMock.DisconnectedFunc: method is nil but CoordinatorClientInterface.Disconnected was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDisconnected.Lock()
	mock.calls.Disconnected = append(mock.calls.Disconnected, callInfo)
	mock.lockDisconnected.Unlock()
	return mock.DisconnectedFunc()
}

// DisconnectedCalls gets all the calls that were made to Disconnected.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.DisconnectedCalls())
func (mock *CoordinatorClientInterfaceMock) DisconnectedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDisconnected.RLock()
	calls = mock.calls.Disconnected
	mock.lockDisconnected.RUnlock()
	return calls
}

// GetInterceptor calls GetInterceptorFunc.
func (mock *CoordinatorClientInterfaceMock) GetInterceptor() *event.Store[models.WebsocketEvent] {
	if mock.GetInterceptorFunc == nil {
		panic("CoordinatorClientInterfaceMock.GetInterceptorFunc: method is nil but CoordinatorClientInterface.GetInterceptor was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetInterceptor.Lock()
	mock.calls.GetInterceptor = append(mock.calls.GetInterceptor, callInfo)
	mock.lockGetInterceptor.Unlock()
	return mock.GetInterceptorFunc()
}

// GetInterceptorCalls gets all the calls that were made to GetInterceptor.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.GetInterceptorCalls())
func (mock *CoordinatorClientInterfaceMock) GetInterceptorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetInterceptor.RLock()
	calls = mock.calls.GetInterceptor
	mock.lockGetInterceptor.RUnlock()
	return calls
}

// JoinCall calls JoinCallFunc.
func (mock *CoordinatorClientInterfaceMock) JoinCall(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest) (models.JoinCallResponse, error) {
	if mock.JoinCallFunc == nil {
		panic("CoordinatorClientInterfaceMock.JoinCallFunc: method is nil but CoordinatorClientInterface.JoinCall was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
	}{
		Ctx:             ctx,
		_type:           _type,
		ID:              id,
		JoinCallRequest: joinCallRequest,
	}
	mock.lockJoinCall.Lock()
	mock.calls.JoinCall = append(mock.calls.JoinCall, callInfo)
	mock.lockJoinCall.Unlock()
	return mock.JoinCallFunc(ctx, _type, id, joinCallRequest)
}

// JoinCallCalls gets all the calls that were made to JoinCall.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.JoinCallCalls())
func (mock *CoordinatorClientInterfaceMock) JoinCallCalls() []struct {
	Ctx             context.Context
	_type           string
	ID              string
	JoinCallRequest models.JoinCallRequest
} {
	var calls []struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
	}
	mock.lockJoinCall.RLock()
	calls = mock.calls.JoinCall
	mock.lockJoinCall.RUnlock()
	return calls
}

// WatchCall calls WatchCallFunc.
func (mock *CoordinatorClientInterfaceMock) WatchCall(ctx context.Context, _type string, id string, connectionID string) error {
	if mock.WatchCallFunc == nil {
		panic("CoordinatorClientInterfaceMock.WatchCallFunc: method is nil but CoordinatorClientInterface.WatchCall was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		_type        string
		ID           string
		ConnectionID string
	}{
		Ctx:          ctx,
		_type:        _type,
		ID:           id,
		ConnectionID: connectionID,
	}
	mock.lockWatchCall.Lock()
	mock.calls.WatchCall = append(mock.calls.WatchCall, callInfo)
	mock.lockWatchCall.Unlock()
	return mock.WatchCallFunc(ctx, _type, id, connectionID)
}

// WatchCallCalls gets all the calls that were made to WatchCall.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.WatchCallCalls())
func (mock *CoordinatorClientInterfaceMock) WatchCallCalls() []struct {
	Ctx          context.Context
	_type        string
	ID           string
	ConnectionID string
} {
	var calls []struct {
		Ctx          context.Context
		_type        string
		ID           string
		ConnectionID string
	}
	mock.lockWatchCall.RLock()
	calls = mock.calls.WatchCall
	mock.lockWatchCall.RUnlock()
	return calls
}
