// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/GetStream/getstream-go-webrtc/coordinator"
	models "github.com/GetStream/getstream-go-webrtc/coordinator/models"
	"github.com/GetStream/getstream-go-webrtc/event"
	"sync"
)

// Ensure, that CoordinatorClientInterfaceMock does implement coordinator.CoordinatorClientInterface.
// If this is not the case, regenerate this file with moq.
var _ coordinator.CoordinatorClientInterface = &CoordinatorClientInterfaceMock{}

// CoordinatorClientInterfaceMock is a mock implementation of coordinator.CoordinatorClientInterface.
//
//	func TestSomethingThatUsesCoordinatorClientInterface(t *testing.T) {
//
//		// make and configure a mocked coordinator.CoordinatorClientInterface
//		mockedCoordinatorClientInterface := &CoordinatorClientInterfaceMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ConnectFunc: func(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error) {
//				panic("mock out the Connect method")
//			},
//			GetInterceptorFunc: func() *event.Store[models.WebsocketEvent] {
//				panic("mock out the GetInterceptor method")
//			},
//			JoinCallFunc: func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest, connectionID *string) (models.JoinCallResponse, error) {
//				panic("mock out the JoinCall method")
//			},
//		}
//
//		// use mockedCoordinatorClientInterface in code that requires coordinator.CoordinatorClientInterface
//		// and then make assertions.
//
//	}
type CoordinatorClientInterfaceMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ConnectFunc mocks the Connect method.
	ConnectFunc func(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error)

	// GetInterceptorFunc mocks the GetInterceptor method.
	GetInterceptorFunc func() *event.Store[models.WebsocketEvent]

	// JoinCallFunc mocks the JoinCall method.
	JoinCallFunc func(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest, connectionID *string) (models.JoinCallResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Connect holds details about calls to the Connect method.
		Connect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JoinRequest is the joinRequest argument value.
			JoinRequest *models.WSAuthMessage
		}
		// GetInterceptor holds details about calls to the GetInterceptor method.
		GetInterceptor []struct {
		}
		// JoinCall holds details about calls to the JoinCall method.
		JoinCall []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// _type is the _type argument value.
			_type string
			// ID is the id argument value.
			ID string
			// JoinCallRequest is the joinCallRequest argument value.
			JoinCallRequest models.JoinCallRequest
			// ConnectionID is the connectionID argument value.
			ConnectionID *string
		}
	}
	lockClose          sync.RWMutex
	lockConnect        sync.RWMutex
	lockGetInterceptor sync.RWMutex
	lockJoinCall       sync.RWMutex
}

// Close calls CloseFunc.
func (mock *CoordinatorClientInterfaceMock) Close() error {
	if mock.CloseFunc == nil {
		panic("CoordinatorClientInterfaceMock.CloseFunc: method is nil but CoordinatorClientInterface.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.CloseCalls())
func (mock *CoordinatorClientInterfaceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Connect calls ConnectFunc.
func (mock *CoordinatorClientInterfaceMock) Connect(ctx context.Context, joinRequest *models.WSAuthMessage) (*models.ConnectedEvent, error) {
	if mock.ConnectFunc == nil {
		panic("CoordinatorClientInterfaceMock.ConnectFunc: method is nil but CoordinatorClientInterface.Connect was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		JoinRequest *models.WSAuthMessage
	}{
		Ctx:         ctx,
		JoinRequest: joinRequest,
	}
	mock.lockConnect.Lock()
	mock.calls.Connect = append(mock.calls.Connect, callInfo)
	mock.lockConnect.Unlock()
	return mock.ConnectFunc(ctx, joinRequest)
}

// ConnectCalls gets all the calls that were made to Connect.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.ConnectCalls())
func (mock *CoordinatorClientInterfaceMock) ConnectCalls() []struct {
	Ctx         context.Context
	JoinRequest *models.WSAuthMessage
} {
	var calls []struct {
		Ctx         context.Context
		JoinRequest *models.WSAuthMessage
	}
	mock.lockConnect.RLock()
	calls = mock.calls.Connect
	mock.lockConnect.RUnlock()
	return calls
}

// GetInterceptor calls GetInterceptorFunc.
func (mock *CoordinatorClientInterfaceMock) GetInterceptor() *event.Store[models.WebsocketEvent] {
	if mock.GetInterceptorFunc == nil {
		panic("CoordinatorClientInterfaceMock.GetInterceptorFunc: method is nil but CoordinatorClientInterface.GetInterceptor was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetInterceptor.Lock()
	mock.calls.GetInterceptor = append(mock.calls.GetInterceptor, callInfo)
	mock.lockGetInterceptor.Unlock()
	return mock.GetInterceptorFunc()
}

// GetInterceptorCalls gets all the calls that were made to GetInterceptor.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.GetInterceptorCalls())
func (mock *CoordinatorClientInterfaceMock) GetInterceptorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetInterceptor.RLock()
	calls = mock.calls.GetInterceptor
	mock.lockGetInterceptor.RUnlock()
	return calls
}

// JoinCall calls JoinCallFunc.
func (mock *CoordinatorClientInterfaceMock) JoinCall(ctx context.Context, _type string, id string, joinCallRequest models.JoinCallRequest, connectionID *string) (models.JoinCallResponse, error) {
	if mock.JoinCallFunc == nil {
		panic("CoordinatorClientInterfaceMock.JoinCallFunc: method is nil but CoordinatorClientInterface.JoinCall was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
		ConnectionID    *string
	}{
		Ctx:             ctx,
		_type:           _type,
		ID:              id,
		JoinCallRequest: joinCallRequest,
		ConnectionID:    connectionID,
	}
	mock.lockJoinCall.Lock()
	mock.calls.JoinCall = append(mock.calls.JoinCall, callInfo)
	mock.lockJoinCall.Unlock()
	return mock.JoinCallFunc(ctx, _type, id, joinCallRequest, connectionID)
}

// JoinCallCalls gets all the calls that were made to JoinCall.
// Check the length with:
//
//	len(mockedCoordinatorClientInterface.JoinCallCalls())
func (mock *CoordinatorClientInterfaceMock) JoinCallCalls() []struct {
	Ctx             context.Context
	_type           string
	ID              string
	JoinCallRequest models.JoinCallRequest
	ConnectionID    *string
} {
	var calls []struct {
		Ctx             context.Context
		_type           string
		ID              string
		JoinCallRequest models.JoinCallRequest
		ConnectionID    *string
	}
	mock.lockJoinCall.RLock()
	calls = mock.calls.JoinCall
	mock.lockJoinCall.RUnlock()
	return calls
}
