// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package signal

import sfuevent "github.com/GetStream/protocol/protobuf/video/sfu/event"

// Events constrains the event types HandleEvent and AwaitEvent accept.
//
// Every member is an SfuEvent_* oneof wrapper, because that is what
// SfuEvent.GetEventPayload returns and therefore what both HandleEvent and the
// event store match on. Listing an inner message type here would compile and
// never match, which is why the list is generated from the oneof itself.
type Events interface {
	*sfuevent.SfuEvent_AudioLevelChanged |
		*sfuevent.SfuEvent_CallEnded |
		*sfuevent.SfuEvent_CallGrantsUpdated |
		*sfuevent.SfuEvent_ChangePublishOptions |
		*sfuevent.SfuEvent_ChangePublishQuality |
		*sfuevent.SfuEvent_ConnectionQualityChanged |
		*sfuevent.SfuEvent_DominantSpeakerChanged |
		*sfuevent.SfuEvent_Error |
		*sfuevent.SfuEvent_GoAway |
		*sfuevent.SfuEvent_HealthCheckResponse |
		*sfuevent.SfuEvent_IceRestart |
		*sfuevent.SfuEvent_IceTrickle |
		*sfuevent.SfuEvent_InboundStateNotification |
		*sfuevent.SfuEvent_JoinResponse |
		*sfuevent.SfuEvent_ParticipantJoined |
		*sfuevent.SfuEvent_ParticipantLeft |
		*sfuevent.SfuEvent_ParticipantMigrationComplete |
		*sfuevent.SfuEvent_ParticipantUpdated |
		*sfuevent.SfuEvent_PinsUpdated |
		*sfuevent.SfuEvent_PublisherAnswer |
		*sfuevent.SfuEvent_SubscriberOffer |
		*sfuevent.SfuEvent_TrackPublished |
		*sfuevent.SfuEvent_TrackUnpublished
}
