// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package coordinator

import models "github.com/GetStream/getstream-go-webrtc/coordinator/models"

// Events constrains the event types HandleEvent and AwaitEvent accept.
type Events interface {
	*models.AppUpdatedEvent |
		*models.BlockedUserEvent |
		*models.CallAcceptedEvent |
		*models.CallClosedCaptionsFailedEvent |
		*models.CallClosedCaptionsStartedEvent |
		*models.CallClosedCaptionsStoppedEvent |
		*models.CallCreatedEvent |
		*models.CallDTMFEvent |
		*models.CallDeletedEvent |
		*models.CallEndedEvent |
		*models.CallFrameRecordingFailedEvent |
		*models.CallFrameRecordingFrameReadyEvent |
		*models.CallFrameRecordingStartedEvent |
		*models.CallFrameRecordingStoppedEvent |
		*models.CallHLSBroadcastingFailedEvent |
		*models.CallHLSBroadcastingStartedEvent |
		*models.CallHLSBroadcastingStoppedEvent |
		*models.CallLiveStartedEvent |
		*models.CallMemberAddedEvent |
		*models.CallMemberRemovedEvent |
		*models.CallMemberUpdatedEvent |
		*models.CallMemberUpdatedPermissionEvent |
		*models.CallMissedEvent |
		*models.CallModerationBlurEvent |
		*models.CallModerationWarningEvent |
		*models.CallNotificationEvent |
		*models.CallReactionEvent |
		*models.CallRecordingFailedEvent |
		*models.CallRecordingReadyEvent |
		*models.CallRecordingStartedEvent |
		*models.CallRecordingStoppedEvent |
		*models.CallRejectedEvent |
		*models.CallRingEvent |
		*models.CallRtmpBroadcastFailedEvent |
		*models.CallRtmpBroadcastStartedEvent |
		*models.CallRtmpBroadcastStoppedEvent |
		*models.CallSessionEndedEvent |
		*models.CallSessionParticipantCountsUpdatedEvent |
		*models.CallSessionParticipantJoinedEvent |
		*models.CallSessionParticipantLeftEvent |
		*models.CallSessionStartedEvent |
		*models.CallStatsReportReadyEvent |
		*models.CallTranscriptionFailedEvent |
		*models.CallTranscriptionReadyEvent |
		*models.CallTranscriptionStartedEvent |
		*models.CallTranscriptionStoppedEvent |
		*models.CallUpdatedEvent |
		*models.CallUserFeedbackSubmittedEvent |
		*models.CallUserMutedEvent |
		*models.ClosedCaptionEvent |
		*models.ConnectedEvent |
		*models.ConnectionErrorEvent |
		*models.CustomVideoEvent |
		*models.HealthCheckEvent |
		*models.IngressErrorEvent |
		*models.IngressStartedEvent |
		*models.IngressStoppedEvent |
		*models.KickedUserEvent |
		*models.PermissionRequestEvent |
		*models.UnblockedUserEvent |
		*models.UpdatedCallPermissionsEvent |
		*models.UserBannedEvent |
		*models.UserDeactivatedEvent |
		*models.UserDeletedEvent |
		*models.UserPresenceChangedEvent |
		*models.UserReactivatedEvent |
		*models.UserUnbannedEvent |
		*models.UserUpdatedEvent
}

// CallEvents constrains the events that belong to a specific call, i.e.
// those carrying a call_cid.
type CallEvents interface {
	*models.BlockedUserEvent |
		*models.CallAcceptedEvent |
		*models.CallClosedCaptionsFailedEvent |
		*models.CallClosedCaptionsStartedEvent |
		*models.CallClosedCaptionsStoppedEvent |
		*models.CallCreatedEvent |
		*models.CallDTMFEvent |
		*models.CallDeletedEvent |
		*models.CallEndedEvent |
		*models.CallFrameRecordingFailedEvent |
		*models.CallFrameRecordingFrameReadyEvent |
		*models.CallFrameRecordingStartedEvent |
		*models.CallFrameRecordingStoppedEvent |
		*models.CallHLSBroadcastingFailedEvent |
		*models.CallHLSBroadcastingStartedEvent |
		*models.CallHLSBroadcastingStoppedEvent |
		*models.CallLiveStartedEvent |
		*models.CallMemberAddedEvent |
		*models.CallMemberRemovedEvent |
		*models.CallMemberUpdatedEvent |
		*models.CallMemberUpdatedPermissionEvent |
		*models.CallMissedEvent |
		*models.CallModerationBlurEvent |
		*models.CallModerationWarningEvent |
		*models.CallNotificationEvent |
		*models.CallReactionEvent |
		*models.CallRecordingFailedEvent |
		*models.CallRecordingReadyEvent |
		*models.CallRecordingStartedEvent |
		*models.CallRecordingStoppedEvent |
		*models.CallRejectedEvent |
		*models.CallRingEvent |
		*models.CallRtmpBroadcastFailedEvent |
		*models.CallRtmpBroadcastStartedEvent |
		*models.CallRtmpBroadcastStoppedEvent |
		*models.CallSessionEndedEvent |
		*models.CallSessionParticipantCountsUpdatedEvent |
		*models.CallSessionParticipantJoinedEvent |
		*models.CallSessionParticipantLeftEvent |
		*models.CallSessionStartedEvent |
		*models.CallStatsReportReadyEvent |
		*models.CallTranscriptionFailedEvent |
		*models.CallTranscriptionReadyEvent |
		*models.CallTranscriptionStartedEvent |
		*models.CallTranscriptionStoppedEvent |
		*models.CallUpdatedEvent |
		*models.CallUserFeedbackSubmittedEvent |
		*models.CallUserMutedEvent |
		*models.ClosedCaptionEvent |
		*models.CustomVideoEvent |
		*models.IngressErrorEvent |
		*models.IngressStartedEvent |
		*models.IngressStoppedEvent |
		*models.KickedUserEvent |
		*models.PermissionRequestEvent |
		*models.UnblockedUserEvent |
		*models.UpdatedCallPermissionsEvent
}

// getCallCid returns the call a call-scoped event belongs to.
func getCallCid[T CallEvents](e T) string {
	switch e := any(e).(type) {
	case *models.BlockedUserEvent:
		return e.CallCid
	case *models.CallAcceptedEvent:
		return e.CallCid
	case *models.CallClosedCaptionsFailedEvent:
		return e.CallCid
	case *models.CallClosedCaptionsStartedEvent:
		return e.CallCid
	case *models.CallClosedCaptionsStoppedEvent:
		return e.CallCid
	case *models.CallCreatedEvent:
		return e.CallCid
	case *models.CallDTMFEvent:
		return e.CallCid
	case *models.CallDeletedEvent:
		return e.CallCid
	case *models.CallEndedEvent:
		return e.CallCid
	case *models.CallFrameRecordingFailedEvent:
		return e.CallCid
	case *models.CallFrameRecordingFrameReadyEvent:
		return e.CallCid
	case *models.CallFrameRecordingStartedEvent:
		return e.CallCid
	case *models.CallFrameRecordingStoppedEvent:
		return e.CallCid
	case *models.CallHLSBroadcastingFailedEvent:
		return e.CallCid
	case *models.CallHLSBroadcastingStartedEvent:
		return e.CallCid
	case *models.CallHLSBroadcastingStoppedEvent:
		return e.CallCid
	case *models.CallLiveStartedEvent:
		return e.CallCid
	case *models.CallMemberAddedEvent:
		return e.CallCid
	case *models.CallMemberRemovedEvent:
		return e.CallCid
	case *models.CallMemberUpdatedEvent:
		return e.CallCid
	case *models.CallMemberUpdatedPermissionEvent:
		return e.CallCid
	case *models.CallMissedEvent:
		return e.CallCid
	case *models.CallModerationBlurEvent:
		return e.CallCid
	case *models.CallModerationWarningEvent:
		return e.CallCid
	case *models.CallNotificationEvent:
		return e.CallCid
	case *models.CallReactionEvent:
		return e.CallCid
	case *models.CallRecordingFailedEvent:
		return e.CallCid
	case *models.CallRecordingReadyEvent:
		return e.CallCid
	case *models.CallRecordingStartedEvent:
		return e.CallCid
	case *models.CallRecordingStoppedEvent:
		return e.CallCid
	case *models.CallRejectedEvent:
		return e.CallCid
	case *models.CallRingEvent:
		return e.CallCid
	case *models.CallRtmpBroadcastFailedEvent:
		return e.CallCid
	case *models.CallRtmpBroadcastStartedEvent:
		return e.CallCid
	case *models.CallRtmpBroadcastStoppedEvent:
		return e.CallCid
	case *models.CallSessionEndedEvent:
		return e.CallCid
	case *models.CallSessionParticipantCountsUpdatedEvent:
		return e.CallCid
	case *models.CallSessionParticipantJoinedEvent:
		return e.CallCid
	case *models.CallSessionParticipantLeftEvent:
		return e.CallCid
	case *models.CallSessionStartedEvent:
		return e.CallCid
	case *models.CallStatsReportReadyEvent:
		return e.CallCid
	case *models.CallTranscriptionFailedEvent:
		return e.CallCid
	case *models.CallTranscriptionReadyEvent:
		return e.CallCid
	case *models.CallTranscriptionStartedEvent:
		return e.CallCid
	case *models.CallTranscriptionStoppedEvent:
		return e.CallCid
	case *models.CallUpdatedEvent:
		return e.CallCid
	case *models.CallUserFeedbackSubmittedEvent:
		return e.CallCid
	case *models.CallUserMutedEvent:
		return e.CallCid
	case *models.ClosedCaptionEvent:
		return e.CallCid
	case *models.CustomVideoEvent:
		return e.CallCid
	case *models.IngressErrorEvent:
		return e.CallCid
	case *models.IngressStartedEvent:
		return e.CallCid
	case *models.IngressStoppedEvent:
		return e.CallCid
	case *models.KickedUserEvent:
		return e.CallCid
	case *models.PermissionRequestEvent:
		return e.CallCid
	case *models.UnblockedUserEvent:
		return e.CallCid
	case *models.UpdatedCallPermissionsEvent:
		return e.CallCid
	default:
		return ""
	}
}

// dispatch routes an event to the matching Handler callback. It reports
// whether the event was recognised.
func dispatch(h Handler, e models.WebsocketEvent) bool {
	switch e := e.(type) {
	case *models.AppUpdatedEvent:
		h.OnAppUpdatedEvent(e)
	case *models.BlockedUserEvent:
		h.OnBlockedUserEvent(e)
	case *models.CallAcceptedEvent:
		h.OnCallAcceptedEvent(e)
	case *models.CallClosedCaptionsFailedEvent:
		h.OnCallClosedCaptionsFailedEvent(e)
	case *models.CallClosedCaptionsStartedEvent:
		h.OnCallClosedCaptionsStartedEvent(e)
	case *models.CallClosedCaptionsStoppedEvent:
		h.OnCallClosedCaptionsStoppedEvent(e)
	case *models.CallCreatedEvent:
		h.OnCallCreatedEvent(e)
	case *models.CallDTMFEvent:
		h.OnCallDTMFEvent(e)
	case *models.CallDeletedEvent:
		h.OnCallDeletedEvent(e)
	case *models.CallEndedEvent:
		h.OnCallEndedEvent(e)
	case *models.CallFrameRecordingFailedEvent:
		h.OnCallFrameRecordingFailedEvent(e)
	case *models.CallFrameRecordingFrameReadyEvent:
		h.OnCallFrameRecordingFrameReadyEvent(e)
	case *models.CallFrameRecordingStartedEvent:
		h.OnCallFrameRecordingStartedEvent(e)
	case *models.CallFrameRecordingStoppedEvent:
		h.OnCallFrameRecordingStoppedEvent(e)
	case *models.CallHLSBroadcastingFailedEvent:
		h.OnCallHLSBroadcastingFailedEvent(e)
	case *models.CallHLSBroadcastingStartedEvent:
		h.OnCallHLSBroadcastingStartedEvent(e)
	case *models.CallHLSBroadcastingStoppedEvent:
		h.OnCallHLSBroadcastingStoppedEvent(e)
	case *models.CallLiveStartedEvent:
		h.OnCallLiveStartedEvent(e)
	case *models.CallMemberAddedEvent:
		h.OnCallMemberAddedEvent(e)
	case *models.CallMemberRemovedEvent:
		h.OnCallMemberRemovedEvent(e)
	case *models.CallMemberUpdatedEvent:
		h.OnCallMemberUpdatedEvent(e)
	case *models.CallMemberUpdatedPermissionEvent:
		h.OnCallMemberUpdatedPermissionEvent(e)
	case *models.CallMissedEvent:
		h.OnCallMissedEvent(e)
	case *models.CallModerationBlurEvent:
		h.OnCallModerationBlurEvent(e)
	case *models.CallModerationWarningEvent:
		h.OnCallModerationWarningEvent(e)
	case *models.CallNotificationEvent:
		h.OnCallNotificationEvent(e)
	case *models.CallReactionEvent:
		h.OnCallReactionEvent(e)
	case *models.CallRecordingFailedEvent:
		h.OnCallRecordingFailedEvent(e)
	case *models.CallRecordingReadyEvent:
		h.OnCallRecordingReadyEvent(e)
	case *models.CallRecordingStartedEvent:
		h.OnCallRecordingStartedEvent(e)
	case *models.CallRecordingStoppedEvent:
		h.OnCallRecordingStoppedEvent(e)
	case *models.CallRejectedEvent:
		h.OnCallRejectedEvent(e)
	case *models.CallRingEvent:
		h.OnCallRingEvent(e)
	case *models.CallRtmpBroadcastFailedEvent:
		h.OnCallRtmpBroadcastFailedEvent(e)
	case *models.CallRtmpBroadcastStartedEvent:
		h.OnCallRtmpBroadcastStartedEvent(e)
	case *models.CallRtmpBroadcastStoppedEvent:
		h.OnCallRtmpBroadcastStoppedEvent(e)
	case *models.CallSessionEndedEvent:
		h.OnCallSessionEndedEvent(e)
	case *models.CallSessionParticipantCountsUpdatedEvent:
		h.OnCallSessionParticipantCountsUpdatedEvent(e)
	case *models.CallSessionParticipantJoinedEvent:
		h.OnCallSessionParticipantJoinedEvent(e)
	case *models.CallSessionParticipantLeftEvent:
		h.OnCallSessionParticipantLeftEvent(e)
	case *models.CallSessionStartedEvent:
		h.OnCallSessionStartedEvent(e)
	case *models.CallStatsReportReadyEvent:
		h.OnCallStatsReportReadyEvent(e)
	case *models.CallTranscriptionFailedEvent:
		h.OnCallTranscriptionFailedEvent(e)
	case *models.CallTranscriptionReadyEvent:
		h.OnCallTranscriptionReadyEvent(e)
	case *models.CallTranscriptionStartedEvent:
		h.OnCallTranscriptionStartedEvent(e)
	case *models.CallTranscriptionStoppedEvent:
		h.OnCallTranscriptionStoppedEvent(e)
	case *models.CallUpdatedEvent:
		h.OnCallUpdatedEvent(e)
	case *models.CallUserFeedbackSubmittedEvent:
		h.OnCallUserFeedbackSubmittedEvent(e)
	case *models.CallUserMutedEvent:
		h.OnCallUserMutedEvent(e)
	case *models.ClosedCaptionEvent:
		h.OnClosedCaptionEvent(e)
	case *models.ConnectedEvent:
		h.OnConnectedEvent(e)
	case *models.ConnectionErrorEvent:
		h.OnConnectionErrorEvent(e)
	case *models.CustomVideoEvent:
		h.OnCustomVideoEvent(e)
	case *models.HealthCheckEvent:
		h.OnHealthCheckEvent(e)
	case *models.IngressErrorEvent:
		h.OnIngressErrorEvent(e)
	case *models.IngressStartedEvent:
		h.OnIngressStartedEvent(e)
	case *models.IngressStoppedEvent:
		h.OnIngressStoppedEvent(e)
	case *models.KickedUserEvent:
		h.OnKickedUserEvent(e)
	case *models.PermissionRequestEvent:
		h.OnPermissionRequestEvent(e)
	case *models.UnblockedUserEvent:
		h.OnUnblockedUserEvent(e)
	case *models.UpdatedCallPermissionsEvent:
		h.OnUpdatedCallPermissionsEvent(e)
	case *models.UserBannedEvent:
		h.OnUserBannedEvent(e)
	case *models.UserDeactivatedEvent:
		h.OnUserDeactivatedEvent(e)
	case *models.UserDeletedEvent:
		h.OnUserDeletedEvent(e)
	case *models.UserPresenceChangedEvent:
		h.OnUserPresenceChangedEvent(e)
	case *models.UserReactivatedEvent:
		h.OnUserReactivatedEvent(e)
	case *models.UserUnbannedEvent:
		h.OnUserUnbannedEvent(e)
	case *models.UserUpdatedEvent:
		h.OnUserUpdatedEvent(e)
	default:
		return false
	}
	return true
}
