// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package coordinator

import models "github.com/GetStream/getstream-go-webrtc/coordinator/models"

// Handler receives every event the coordinator websocket delivers.
// Embed NoopHandler to implement only the callbacks you care about.
type Handler interface {
	OnAppUpdatedEvent(*models.AppUpdatedEvent)
	OnBlockedUserEvent(*models.BlockedUserEvent)
	OnCallAcceptedEvent(*models.CallAcceptedEvent)
	OnCallClosedCaptionsFailedEvent(*models.CallClosedCaptionsFailedEvent)
	OnCallClosedCaptionsStartedEvent(*models.CallClosedCaptionsStartedEvent)
	OnCallClosedCaptionsStoppedEvent(*models.CallClosedCaptionsStoppedEvent)
	OnCallCreatedEvent(*models.CallCreatedEvent)
	OnCallDTMFEvent(*models.CallDTMFEvent)
	OnCallDeletedEvent(*models.CallDeletedEvent)
	OnCallEndedEvent(*models.CallEndedEvent)
	OnCallFrameRecordingFailedEvent(*models.CallFrameRecordingFailedEvent)
	OnCallFrameRecordingFrameReadyEvent(*models.CallFrameRecordingFrameReadyEvent)
	OnCallFrameRecordingStartedEvent(*models.CallFrameRecordingStartedEvent)
	OnCallFrameRecordingStoppedEvent(*models.CallFrameRecordingStoppedEvent)
	OnCallHLSBroadcastingFailedEvent(*models.CallHLSBroadcastingFailedEvent)
	OnCallHLSBroadcastingStartedEvent(*models.CallHLSBroadcastingStartedEvent)
	OnCallHLSBroadcastingStoppedEvent(*models.CallHLSBroadcastingStoppedEvent)
	OnCallLiveStartedEvent(*models.CallLiveStartedEvent)
	OnCallMemberAddedEvent(*models.CallMemberAddedEvent)
	OnCallMemberRemovedEvent(*models.CallMemberRemovedEvent)
	OnCallMemberUpdatedEvent(*models.CallMemberUpdatedEvent)
	OnCallMemberUpdatedPermissionEvent(*models.CallMemberUpdatedPermissionEvent)
	OnCallMissedEvent(*models.CallMissedEvent)
	OnCallModerationBlurEvent(*models.CallModerationBlurEvent)
	OnCallModerationWarningEvent(*models.CallModerationWarningEvent)
	OnCallNotificationEvent(*models.CallNotificationEvent)
	OnCallReactionEvent(*models.CallReactionEvent)
	OnCallRecordingFailedEvent(*models.CallRecordingFailedEvent)
	OnCallRecordingReadyEvent(*models.CallRecordingReadyEvent)
	OnCallRecordingStartedEvent(*models.CallRecordingStartedEvent)
	OnCallRecordingStoppedEvent(*models.CallRecordingStoppedEvent)
	OnCallRejectedEvent(*models.CallRejectedEvent)
	OnCallRingEvent(*models.CallRingEvent)
	OnCallRtmpBroadcastFailedEvent(*models.CallRtmpBroadcastFailedEvent)
	OnCallRtmpBroadcastStartedEvent(*models.CallRtmpBroadcastStartedEvent)
	OnCallRtmpBroadcastStoppedEvent(*models.CallRtmpBroadcastStoppedEvent)
	OnCallSessionEndedEvent(*models.CallSessionEndedEvent)
	OnCallSessionParticipantCountsUpdatedEvent(*models.CallSessionParticipantCountsUpdatedEvent)
	OnCallSessionParticipantJoinedEvent(*models.CallSessionParticipantJoinedEvent)
	OnCallSessionParticipantLeftEvent(*models.CallSessionParticipantLeftEvent)
	OnCallSessionStartedEvent(*models.CallSessionStartedEvent)
	OnCallStatsReportReadyEvent(*models.CallStatsReportReadyEvent)
	OnCallTranscriptionFailedEvent(*models.CallTranscriptionFailedEvent)
	OnCallTranscriptionReadyEvent(*models.CallTranscriptionReadyEvent)
	OnCallTranscriptionStartedEvent(*models.CallTranscriptionStartedEvent)
	OnCallTranscriptionStoppedEvent(*models.CallTranscriptionStoppedEvent)
	OnCallUpdatedEvent(*models.CallUpdatedEvent)
	OnCallUserFeedbackSubmittedEvent(*models.CallUserFeedbackSubmittedEvent)
	OnCallUserMutedEvent(*models.CallUserMutedEvent)
	OnClosedCaptionEvent(*models.ClosedCaptionEvent)
	OnConnectedEvent(*models.ConnectedEvent)
	OnConnectionErrorEvent(*models.ConnectionErrorEvent)
	OnCustomVideoEvent(*models.CustomVideoEvent)
	OnHealthCheckEvent(*models.HealthCheckEvent)
	OnIngressErrorEvent(*models.IngressErrorEvent)
	OnIngressStartedEvent(*models.IngressStartedEvent)
	OnIngressStoppedEvent(*models.IngressStoppedEvent)
	OnKickedUserEvent(*models.KickedUserEvent)
	OnPermissionRequestEvent(*models.PermissionRequestEvent)
	OnUnblockedUserEvent(*models.UnblockedUserEvent)
	OnUpdatedCallPermissionsEvent(*models.UpdatedCallPermissionsEvent)
	OnUserBannedEvent(*models.UserBannedEvent)
	OnUserDeactivatedEvent(*models.UserDeactivatedEvent)
	OnUserDeletedEvent(*models.UserDeletedEvent)
	OnUserPresenceChangedEvent(*models.UserPresenceChangedEvent)
	OnUserReactivatedEvent(*models.UserReactivatedEvent)
	OnUserUnbannedEvent(*models.UserUnbannedEvent)
	OnUserUpdatedEvent(*models.UserUpdatedEvent)
}

// NoopHandler ignores every event.
type NoopHandler struct{}

var _ Handler = NoopHandler{}

func (NoopHandler) OnAppUpdatedEvent(*models.AppUpdatedEvent)                                     {}
func (NoopHandler) OnBlockedUserEvent(*models.BlockedUserEvent)                                   {}
func (NoopHandler) OnCallAcceptedEvent(*models.CallAcceptedEvent)                                 {}
func (NoopHandler) OnCallClosedCaptionsFailedEvent(*models.CallClosedCaptionsFailedEvent)         {}
func (NoopHandler) OnCallClosedCaptionsStartedEvent(*models.CallClosedCaptionsStartedEvent)       {}
func (NoopHandler) OnCallClosedCaptionsStoppedEvent(*models.CallClosedCaptionsStoppedEvent)       {}
func (NoopHandler) OnCallCreatedEvent(*models.CallCreatedEvent)                                   {}
func (NoopHandler) OnCallDTMFEvent(*models.CallDTMFEvent)                                         {}
func (NoopHandler) OnCallDeletedEvent(*models.CallDeletedEvent)                                   {}
func (NoopHandler) OnCallEndedEvent(*models.CallEndedEvent)                                       {}
func (NoopHandler) OnCallFrameRecordingFailedEvent(*models.CallFrameRecordingFailedEvent)         {}
func (NoopHandler) OnCallFrameRecordingFrameReadyEvent(*models.CallFrameRecordingFrameReadyEvent) {}
func (NoopHandler) OnCallFrameRecordingStartedEvent(*models.CallFrameRecordingStartedEvent)       {}
func (NoopHandler) OnCallFrameRecordingStoppedEvent(*models.CallFrameRecordingStoppedEvent)       {}
func (NoopHandler) OnCallHLSBroadcastingFailedEvent(*models.CallHLSBroadcastingFailedEvent)       {}
func (NoopHandler) OnCallHLSBroadcastingStartedEvent(*models.CallHLSBroadcastingStartedEvent)     {}
func (NoopHandler) OnCallHLSBroadcastingStoppedEvent(*models.CallHLSBroadcastingStoppedEvent)     {}
func (NoopHandler) OnCallLiveStartedEvent(*models.CallLiveStartedEvent)                           {}
func (NoopHandler) OnCallMemberAddedEvent(*models.CallMemberAddedEvent)                           {}
func (NoopHandler) OnCallMemberRemovedEvent(*models.CallMemberRemovedEvent)                       {}
func (NoopHandler) OnCallMemberUpdatedEvent(*models.CallMemberUpdatedEvent)                       {}
func (NoopHandler) OnCallMemberUpdatedPermissionEvent(*models.CallMemberUpdatedPermissionEvent)   {}
func (NoopHandler) OnCallMissedEvent(*models.CallMissedEvent)                                     {}
func (NoopHandler) OnCallModerationBlurEvent(*models.CallModerationBlurEvent)                     {}
func (NoopHandler) OnCallModerationWarningEvent(*models.CallModerationWarningEvent)               {}
func (NoopHandler) OnCallNotificationEvent(*models.CallNotificationEvent)                         {}
func (NoopHandler) OnCallReactionEvent(*models.CallReactionEvent)                                 {}
func (NoopHandler) OnCallRecordingFailedEvent(*models.CallRecordingFailedEvent)                   {}
func (NoopHandler) OnCallRecordingReadyEvent(*models.CallRecordingReadyEvent)                     {}
func (NoopHandler) OnCallRecordingStartedEvent(*models.CallRecordingStartedEvent)                 {}
func (NoopHandler) OnCallRecordingStoppedEvent(*models.CallRecordingStoppedEvent)                 {}
func (NoopHandler) OnCallRejectedEvent(*models.CallRejectedEvent)                                 {}
func (NoopHandler) OnCallRingEvent(*models.CallRingEvent)                                         {}
func (NoopHandler) OnCallRtmpBroadcastFailedEvent(*models.CallRtmpBroadcastFailedEvent)           {}
func (NoopHandler) OnCallRtmpBroadcastStartedEvent(*models.CallRtmpBroadcastStartedEvent)         {}
func (NoopHandler) OnCallRtmpBroadcastStoppedEvent(*models.CallRtmpBroadcastStoppedEvent)         {}
func (NoopHandler) OnCallSessionEndedEvent(*models.CallSessionEndedEvent)                         {}
func (NoopHandler) OnCallSessionParticipantCountsUpdatedEvent(*models.CallSessionParticipantCountsUpdatedEvent) {
}
func (NoopHandler) OnCallSessionParticipantJoinedEvent(*models.CallSessionParticipantJoinedEvent) {}
func (NoopHandler) OnCallSessionParticipantLeftEvent(*models.CallSessionParticipantLeftEvent)     {}
func (NoopHandler) OnCallSessionStartedEvent(*models.CallSessionStartedEvent)                     {}
func (NoopHandler) OnCallStatsReportReadyEvent(*models.CallStatsReportReadyEvent)                 {}
func (NoopHandler) OnCallTranscriptionFailedEvent(*models.CallTranscriptionFailedEvent)           {}
func (NoopHandler) OnCallTranscriptionReadyEvent(*models.CallTranscriptionReadyEvent)             {}
func (NoopHandler) OnCallTranscriptionStartedEvent(*models.CallTranscriptionStartedEvent)         {}
func (NoopHandler) OnCallTranscriptionStoppedEvent(*models.CallTranscriptionStoppedEvent)         {}
func (NoopHandler) OnCallUpdatedEvent(*models.CallUpdatedEvent)                                   {}
func (NoopHandler) OnCallUserFeedbackSubmittedEvent(*models.CallUserFeedbackSubmittedEvent)       {}
func (NoopHandler) OnCallUserMutedEvent(*models.CallUserMutedEvent)                               {}
func (NoopHandler) OnClosedCaptionEvent(*models.ClosedCaptionEvent)                               {}
func (NoopHandler) OnConnectedEvent(*models.ConnectedEvent)                                       {}
func (NoopHandler) OnConnectionErrorEvent(*models.ConnectionErrorEvent)                           {}
func (NoopHandler) OnCustomVideoEvent(*models.CustomVideoEvent)                                   {}
func (NoopHandler) OnHealthCheckEvent(*models.HealthCheckEvent)                                   {}
func (NoopHandler) OnIngressErrorEvent(*models.IngressErrorEvent)                                 {}
func (NoopHandler) OnIngressStartedEvent(*models.IngressStartedEvent)                             {}
func (NoopHandler) OnIngressStoppedEvent(*models.IngressStoppedEvent)                             {}
func (NoopHandler) OnKickedUserEvent(*models.KickedUserEvent)                                     {}
func (NoopHandler) OnPermissionRequestEvent(*models.PermissionRequestEvent)                       {}
func (NoopHandler) OnUnblockedUserEvent(*models.UnblockedUserEvent)                               {}
func (NoopHandler) OnUpdatedCallPermissionsEvent(*models.UpdatedCallPermissionsEvent)             {}
func (NoopHandler) OnUserBannedEvent(*models.UserBannedEvent)                                     {}
func (NoopHandler) OnUserDeactivatedEvent(*models.UserDeactivatedEvent)                           {}
func (NoopHandler) OnUserDeletedEvent(*models.UserDeletedEvent)                                   {}
func (NoopHandler) OnUserPresenceChangedEvent(*models.UserPresenceChangedEvent)                   {}
func (NoopHandler) OnUserReactivatedEvent(*models.UserReactivatedEvent)                           {}
func (NoopHandler) OnUserUnbannedEvent(*models.UserUnbannedEvent)                                 {}
func (NoopHandler) OnUserUpdatedEvent(*models.UserUpdatedEvent)                                   {}
