// Code generated by internal/cmd/genwsevent. DO NOT EDIT.

package models

// GetEventType implementations, one per websocket event. They are declared
// on the value type so that both T and *T satisfy WebsocketEvent.

func (AppUpdatedEvent) GetEventType() string { return "app.updated" }

func (BlockedUserEvent) GetEventType() string { return "call.blocked_user" }

func (CallAcceptedEvent) GetEventType() string { return "call.accepted" }

func (CallClosedCaptionsFailedEvent) GetEventType() string { return "call.closed_captions_failed" }

func (CallClosedCaptionsStartedEvent) GetEventType() string { return "call.closed_captions_started" }

func (CallClosedCaptionsStoppedEvent) GetEventType() string { return "call.closed_captions_stopped" }

func (CallCreatedEvent) GetEventType() string { return "call.created" }

func (CallDTMFEvent) GetEventType() string { return "call.dtmf" }

func (CallDeletedEvent) GetEventType() string { return "call.deleted" }

func (CallEndedEvent) GetEventType() string { return "call.ended" }

func (CallFrameRecordingFailedEvent) GetEventType() string { return "call.frame_recording_failed" }

func (CallFrameRecordingFrameReadyEvent) GetEventType() string { return "call.frame_recording_ready" }

func (CallFrameRecordingStartedEvent) GetEventType() string { return "call.frame_recording_started" }

func (CallFrameRecordingStoppedEvent) GetEventType() string { return "call.frame_recording_stopped" }

func (CallHLSBroadcastingFailedEvent) GetEventType() string { return "call.hls_broadcasting_failed" }

func (CallHLSBroadcastingStartedEvent) GetEventType() string { return "call.hls_broadcasting_started" }

func (CallHLSBroadcastingStoppedEvent) GetEventType() string { return "call.hls_broadcasting_stopped" }

func (CallLiveStartedEvent) GetEventType() string { return "call.live_started" }

func (CallMemberAddedEvent) GetEventType() string { return "call.member_added" }

func (CallMemberRemovedEvent) GetEventType() string { return "call.member_removed" }

func (CallMemberUpdatedEvent) GetEventType() string { return "call.member_updated" }

func (CallMemberUpdatedPermissionEvent) GetEventType() string {
	return "call.member_updated_permission"
}

func (CallMissedEvent) GetEventType() string { return "call.missed" }

func (CallModerationBlurEvent) GetEventType() string { return "call.moderation_blur" }

func (CallModerationWarningEvent) GetEventType() string { return "call.moderation_warning" }

func (CallNotificationEvent) GetEventType() string { return "call.notification" }

func (CallReactionEvent) GetEventType() string { return "call.reaction_new" }

func (CallRecordingFailedEvent) GetEventType() string { return "call.recording_failed" }

func (CallRecordingReadyEvent) GetEventType() string { return "call.recording_ready" }

func (CallRecordingStartedEvent) GetEventType() string { return "call.recording_started" }

func (CallRecordingStoppedEvent) GetEventType() string { return "call.recording_stopped" }

func (CallRejectedEvent) GetEventType() string { return "call.rejected" }

func (CallRingEvent) GetEventType() string { return "call.ring" }

func (CallRtmpBroadcastFailedEvent) GetEventType() string { return "call.rtmp_broadcast_failed" }

func (CallRtmpBroadcastStartedEvent) GetEventType() string { return "call.rtmp_broadcast_started" }

func (CallRtmpBroadcastStoppedEvent) GetEventType() string { return "call.rtmp_broadcast_stopped" }

func (CallSessionEndedEvent) GetEventType() string { return "call.session_ended" }

func (CallSessionParticipantCountsUpdatedEvent) GetEventType() string {
	return "call.session_participant_count_updated"
}

func (CallSessionParticipantJoinedEvent) GetEventType() string {
	return "call.session_participant_joined"
}

func (CallSessionParticipantLeftEvent) GetEventType() string { return "call.session_participant_left" }

func (CallSessionStartedEvent) GetEventType() string { return "call.session_started" }

func (CallStatsReportReadyEvent) GetEventType() string { return "call.stats_report_ready" }

func (CallTranscriptionFailedEvent) GetEventType() string { return "call.transcription_failed" }

func (CallTranscriptionReadyEvent) GetEventType() string { return "call.transcription_ready" }

func (CallTranscriptionStartedEvent) GetEventType() string { return "call.transcription_started" }

func (CallTranscriptionStoppedEvent) GetEventType() string { return "call.transcription_stopped" }

func (CallUpdatedEvent) GetEventType() string { return "call.updated" }

func (CallUserFeedbackSubmittedEvent) GetEventType() string { return "call.user_feedback_submitted" }

func (CallUserMutedEvent) GetEventType() string { return "call.user_muted" }

func (ClosedCaptionEvent) GetEventType() string { return "call.closed_caption" }

func (ConnectedEvent) GetEventType() string { return "connection.ok" }

func (ConnectionErrorEvent) GetEventType() string { return "connection.error" }

func (CustomVideoEvent) GetEventType() string { return "custom" }

func (HealthCheckEvent) GetEventType() string { return "health.check" }

func (IngressErrorEvent) GetEventType() string { return "ingress.error" }

func (IngressStartedEvent) GetEventType() string { return "ingress.started" }

func (IngressStoppedEvent) GetEventType() string { return "ingress.stopped" }

func (KickedUserEvent) GetEventType() string { return "call.kicked_user" }

func (PermissionRequestEvent) GetEventType() string { return "call.permission_request" }

func (UnblockedUserEvent) GetEventType() string { return "call.unblocked_user" }

func (UpdatedCallPermissionsEvent) GetEventType() string { return "call.permissions_updated" }

func (UserBannedEvent) GetEventType() string { return "user.banned" }

func (UserDeactivatedEvent) GetEventType() string { return "user.deactivated" }

func (UserDeletedEvent) GetEventType() string { return "user.deleted" }

func (UserPresenceChangedEvent) GetEventType() string { return "user.presence.changed" }

func (UserReactivatedEvent) GetEventType() string { return "user.reactivated" }

func (UserUnbannedEvent) GetEventType() string { return "user.unbanned" }

func (UserUpdatedEvent) GetEventType() string { return "user.updated" }
